# Generated by Django 6.0.6 on 2026-07-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('technologies', models.CharField(help_text='Example: Django, Bootstrap, SQLite', max_length=300)),
                ('github_link', models.URLField(blank=True)),
                ('live_demo', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
