# Generated by Django 6.0.6 on 2026-07-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(default='Technology', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='bi bi-code-slash', help_text='Example: bi bi-filetype-html', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='percentage',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
